// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwMSY_e1fOtUUViT306vjJFzb_0XbvlRU',
    appId: '1:227015986946:web:b9d5ffc1ceff7dedbe3c1b',
    messagingSenderId: '227015986946',
    projectId: 'zed-stores',
    authDomain: 'zed-stores.firebaseapp.com',
    storageBucket: 'zed-stores.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo5gqajOHZAPKDpuDK4_44_FtfDMp6qG8',
    appId: '1:227015986946:android:4132aa68678277e7be3c1b',
    messagingSenderId: '227015986946',
    projectId: 'zed-stores',
    storageBucket: 'zed-stores.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMa5T2putcyLoIS48ZsqR3FDn6eVdJt-Q',
    appId: '1:227015986946:ios:ed78e8bea54646c8be3c1b',
    messagingSenderId: '227015986946',
    projectId: 'zed-stores',
    storageBucket: 'zed-stores.appspot.com',
    iosBundleId: 'com.example.zedStores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMa5T2putcyLoIS48ZsqR3FDn6eVdJt-Q',
    appId: '1:227015986946:ios:b4de34e3013e1b03be3c1b',
    messagingSenderId: '227015986946',
    projectId: 'zed-stores',
    storageBucket: 'zed-stores.appspot.com',
    iosBundleId: 'com.example.zedStores.RunnerTests',
  );
}
